fix(scully-plugin-angular-delay): Load JS files
fix(scully-plugin-angular-delay): Load JS files

Currently get error `Uncaught TypeError: scriptsToLoad.forEach is not a function`. This is due to forEach on a string.

closes #34